Fix priority field check
In case there is no issue priority, return None as default so the check
works. Otherwise the error was:

AttributeError: type object 'PropertyHolder' has no attribute 'priority'